name: Health check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Health Check Ping
        uses: jtalk/url-health-check-action@v3
        with:
          url: "https://full-stack-open-pokedex-z5h5.onrender.com/health"
