name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types:
      [opened, synchronize]
      # note that your "main" branch might be called main instead of master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Deploy to Render
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  discord_webhook_success:
    needs: [tag_release]
    runs-on: ubuntu-20.04
    if: ${{ success() }}
    steps:
      - name: Notify Discord for new version
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          severity: info
          details: 'New version deployed'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  discord_webhook_failure:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ failure() }}
    steps:
      - name: Notify Discord for build failure
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: 'Build failed. Commit: ${{ github.sha }}'
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}